# Generated by Django 4.2.20 on 2026-03-25 01:01

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('phase', models.CharField(choices=[('title', 'タイトル'), ('setup', 'セットアップ'), ('placing', 'カード配置中'), ('turn_switch', 'ターン切替'), ('round_result', 'ラウンド結果'), ('game_over', 'ゲーム終了')], default='placing', max_length=20)),
                ('current_player_index', models.IntegerField(default=0)),
                ('round_number', models.IntegerField(default=0)),
                ('game_round', models.IntegerField(default=1)),
                ('dealer_index', models.IntegerField(default=0)),
                ('deck', models.JSONField(default=list)),
                ('round_scores', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('order', models.IntegerField()),
                ('hand', models.JSONField(default=list)),
                ('board_top', models.JSONField(default=list)),
                ('board_middle', models.JSONField(default=list)),
                ('board_bottom', models.JSONField(default=list)),
                ('total_score', models.IntegerField(default=0)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='game.game')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('game', 'order')},
            },
        ),
    ]
