# Generated by Django 4.2.20 on 2026-03-25 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='fantasyland_bonus',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='in_fantasyland',
            field=models.BooleanField(default=False),
        ),
    ]
