# Generated by Django 4.2.20 on 2026-03-25 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_player_fantasyland_bonus_player_in_fantasyland'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='locked_board',
            field=models.JSONField(default=dict),
        ),
    ]
