# Generated by Django 4.2.20 on 2026-04-06 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_player_locked_board'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='fl_saved_hand',
            field=models.JSONField(default=list),
        ),
    ]
