# Generated by Django 4.2.29 on 2026-04-13 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_player_fl_saved_hand'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='ready_next_action',
            field=models.CharField(blank=True, choices=[('next', '次ラウンド'), ('end', 'ゲーム終了')], default=None, max_length=10, null=True),
        ),
    ]
