server {
    listen 80;
    server_name ofc.pocket-dealer.jp www.ofc.pocket-dealer.jp;

    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }
    location / {
        return 301 https://ofc.pocket-dealer.jp$request_uri;
    }
}

server {
    listen 443 ssl;
    http2 on;
    server_name www.ofc.pocket-dealer.jp;

    ssl_certificate     /etc/letsencrypt/live/api-ofc.pocket-dealer.jp/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/api-ofc.pocket-dealer.jp/privkey.pem;
    include /etc/nginx/options-ssl-nginx.conf;

    return 301 https://ofc.pocket-dealer.jp$request_uri;
}

server {
    listen 443 ssl;
    http2 on;
    server_name ofc.pocket-dealer.jp;

    ssl_certificate     /etc/letsencrypt/live/api-ofc.pocket-dealer.jp/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/api-ofc.pocket-dealer.jp/privkey.pem;
    include /etc/nginx/options-ssl-nginx.conf;

    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }

    location ~* \.(js|css|png|jpg|jpeg|gif|ico|svg|woff|woff2)$ {
        expires 1y;
        add_header Cache-Control "public, immutable";
    }
}
